<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim - News Reader</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            
            .center {
                text-align: center;
            }
            .feed-item {
                clear: left;
            }
            
            .feed-item img {
                float: left;
                margin: 0 10px
            }
        </style>
    </head>
    <body>
        <h1 class="center">Slim News reader</h1>
        <div class="center">Latest News</div>

        <?php if($error): ?>
            <p style="color:red;"><?php echo $error_message; ?></p>
        <?php else: ?>
            <?php foreach( $news_lists as $feed): ?>
                <h2><?php echo $feed->getTitle(); ?></h2>
                <p><?php echo $feed->getDescription(); ?></p>
                <ol>
                <?php foreach($feed as $item): ?>
                    <li class="feed-item">
                        <h3>
                            <?php if( $item->getUrl() != '' ): ?>
                            <a href="<?php echo $item->getUrl(); ?>" target="_blank">
                            <?php endif; ?>
                            <?php echo $item->getTitle(); ?>
                            <?php if( $item->getUrl() != '' ): ?>
                            </a>
                            <?php endif; ?>
                        </h3>
                        <p><?php echo $item->getDate()->format('M d, Y'); ?></p>
                        <p><?php echo $item->getSummary(); ?></p>
                    </li>
                <?php endforeach; ?>
                </ol>  
            <?php endforeach; ?>
        <?php endif; ?>
    </body>
</html>
