<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Slim - News Reader</title>
        <!-- Bootstrap -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <link href="css/news-reader.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Slim News Reader</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/">Home</a></li>
              <li><a href="#">Login</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 main">
                <h1 class="page-header">News</h1>
                <?php if($error): ?>
                <div class="alert alert-danger" role="alert">
                    <p><?php echo $error_message; ?></p>
                </div>  
                <?php else: ?>
                    <?php foreach( $news_lists as $feed): ?>
                            <h2 class="subheader"> <?php echo $feed->getTitle(); ?></h2>
                            <p><?php echo $feed->getDescription(); ?></p>
                            <ol class="list-unstyled">
                            <?php foreach($feed as $item): ?>
                                <li class="feed-item clearfix">
                                    <h3 class="h3">
                                        <?php if( $item->getUrl() != '' ): ?>
                                        <a href="<?php echo $item->getUrl(); ?>" target="_blank">
                                        <?php endif; ?>
                                        <?php echo $item->getTitle(); ?>
                                        <?php if( $item->getUrl() != '' ): ?>
                                        </a>
                                        <?php endif; ?>
                                    </h3>
                                    <p><?php echo $item->getDate()->format('M d, Y'); ?></p>
                                    <p><?php echo strip_tags($item->getSummary(), '<img><a><p>'); ?></p>
                                </li>
                            <?php endforeach; ?>
                            </ol>  
                    <?php endforeach; ?>
                <?php endif; ?>
            </div>
            <div class="col-md-4 sidebar">
                <ul class="nav nav-sidebar">
                    <li  <?php if($current_feed === null): ?>class="active"<?php endif; ?>><a href="/">All <?php if($current_feed === null): ?><span class="sr-only">(current)</span> <?php endif; ?></a></li>
                    <?php foreach($available_feeds as $feed_name => $feed_url): ?>
                        <li <?php if($current_feed == $feed_name): ?>class="active"<?php endif; ?>><a href="/<?php echo $feed_name; ?>"><?php echo $feed_name; ?> <?php if($current_feed == $feed_name): ?><span class="sr-only">(current)</span> <?php endif; ?></a></li>
                    <?php endforeach; ?>
                  </ul>
            </div>
        </div>

        
                
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script src="js/jquery.min.js"></script>
        <!-- Include all compiled plugins (below), or include individual files as needed -->
        <script src="js/bootstrap.min.js"></script>
    </body>
</html>
